In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from random import choice, randint

In [4]:
class Produto:
    def __init__(self, Loja, Nome, Valor, Custo):
        self.loja = Loja
        self.nome = Nome
        self.valor = Valor
        self.custo = Custo

In [51]:
lista_pizzas = [Produto('Circunferência', 'Pizza de Calabresa', 59.9, 12),
                Produto('Circunferência', 'Pizza Mista', 49.9, 10),
                Produto('Circunferência', 'Pizza de Pepperoni', 68.90, 13.5),
                Produto('Circunferência', 'Pizza de Portuguesa', 74.9, 15),
                Produto('Circunferência', 'Pizza 4 Queijos', 79.9, 14),
                Produto('Circunferência', 'Pizza Paraense', 84.9, 17)
                ]

lista_lanches = [Produto('Esfera', 'Hamburguer', 17, 3.5),
                 Produto('Esfera', 'X Burguer', 20, 4),
                 Produto('Esfera', 'X Bacon', 23, 4.4),
                 Produto('Esfera', 'Leitão', 34, 6.5),
                 Produto('Esfera', 'X Tudo', 50, 12),
                 Produto('Esfera', 'Da Casa', 27, 5)]

lista_sorvetes =[Produto('Cone', 'Picolé', 15, 3),
                 Produto('Cone', 'Milk Shake', 27, 3),
                 Produto('Cone', 'Sorvete', 28, 5),
                 Produto('Cone', 'caixa P', 45, 10),
                 Produto('Cone', 'Taça', 40, 8),
                 Produto('Cone', 'Sundae', 32, 6)]

empreendimento = {'pizzas':lista_pizzas, 'lanches':lista_lanches, 'sorvetes':lista_sorvetes}

In [69]:
def gerador_dataframe(tamanho_dataframe):
    predataframe = {'Loja':[], 'Produto':[], 'Valor(R$)':[], 'Custo de Produção(R$)':[]}
    for i in range(tamanho_dataframe):
        escolha_loja = choice(['pizzas', 'lanches', 'sorvetes'])
        escollha_produto = randint(0, 5)
        
        objeto_temporario = empreendimento[escolha_loja][escollha_produto]
        
        for contador, conteudo in enumerate(objeto_temporario.__dict__.values()):
            predataframe[list(predataframe.keys())[contador]].append(conteudo)
    
    predataframe = pd.DataFrame(predataframe)
    return predataframe


data_pequeno = gerador_dataframe(10)      
data_grande = gerador_dataframe(100000)

In [73]:
linhas_vazias = np.random.choice(data_pequeno.index, size = 2, replace = True)

data_pequeno.loc[linhas_vazias, :] = np.nan

In [74]:
display(data_pequeno)

             Loja          Produto  Valor(R$)  Custo de Produção(R$)
0            Cone           Sundae       32.0                    6.0
1             NaN              NaN        NaN                    NaN
2          Esfera        X Burguer       20.0                    4.0
3            Cone           Picolé       15.0                    3.0
4            Cone          caixa P       45.0                   10.0
5            Cone          Sorvete       28.0                    5.0
6          Esfera        X Burguer       20.0                    4.0
7  Circunferência  Pizza 4 Queijos       79.9                   14.0
8             NaN              NaN        NaN                    NaN
9            Cone          Sorvete       28.0                    5.0